engines:
  rubocop:
    enabled: false
  golint:
    enabled: false
  gofmt:
    enabled: false
  eslint:
    enabled: false
  csslint:
    enabled: false
ratings:
   paths:
   - app/**
   - lib/**
   - "**.rb"
   - "**.js"
   - "**.css"
   - "**.scss"
exclude_paths:
- spec/**/*
- vendor/**/*
