development:
  user: fedoraAdmin
  password: XmhELPyelqj1m0TK
  url: http://127.0.0.1:8080/fedora
test: &TEST  
  user: fedoraAdmin
  password: XmhELPyelqj1m0TK
  url: http://127.0.0.1:8080/fedora
production:
  user: fedoraAdmin
  password: XmhELPyelqj1m0TK
  url: http://127.0.0.1:8080/fedora
cucumber:
  <<: *TEST
