development:
  jetty_port: 8080
  startup_wait: 30 
  java_opts:
    - "-XX:MaxPermSize=128m" 
    - "-Xmx256m"

test:
  jetty_port: 8983
  startup_wait: 60  
  java_opts:
    - "-XX:MaxPermSize=128m" 
    - "-Xmx256m"

production:
  jetty_port: 8080
  java_opts:
    - "-XX:MaxPermSize=128m" 
    - "-Xmx256m"
