development:
  jetty_port: 8080
  java_opts:
    - "-XX:MaxPermSize=128m" 
    - "-Xmx256m"

test:
  jetty_port: <%= ENV['JETTY_PORT'] %>
  java_opts:
    - "-XX:MaxPermSize=128m" 
    - "-Xmx256m"

production:
  jetty_port: <%= ENV['JETTY_PORT'] %>
  java_opts:
    - "-XX:MaxPermSize=128m" 
    - "-Xmx256m"
