archivist:
  - archivist1@example.com
  - archivist2@example.com
reviewer:
  - reviewer1@example.com
  - archivist1@example.com
  - archivist2@example.com
admin_policy_object_editor:
  - archivist1@example.com
donor:
  - donor1@example.com
researcher:
  - archivist1@example.com
  - researcher1@example.com
patron:
  - patron1@example.com
