# This is a sample config file that does not have multiple solr instances. You will also need to be sure to
# edit the fedora.yml file to match the solr URL for active-fedora. 
development:
  url: "http://127.0.0.1:8080/solr/#/development"

travis:
  hostname: localhost
  port: 8983
  log_level: INFO
  path: /solr/#/test

test: &TEST
  url: "http://127.0.0.1:8080/solr/#/test"
  solr_home: solr

cucumber:
  <<: *TEST
production:
  url: "http://127.0.0.1:8080/solr/#/production"

