# This is a sample config file that does not have multiple solr instances. You will also need to be sure to
# edit the fedora.yml file to match the solr URL for active-fedora. 
development:
  url: "http://127.0.0.1:8080/solr/#/development"
  solr:
    hostname: localhost
    port: 8983
    log_level: INFO
    path: /solr/#/development  
    solr_home: solr


test: &TEST
  url: "http://127.0.0.1:8983/solr/#/test"
  solr:
    hostname: localhost
    port: 8983
    log_level: WARNING
    path: /solr/#/test  
    solr_home: "jetty/solr"

cucumber:
  <<: *TEST
production:
  url: "http://127.0.0.1:8080/solr/#/production"

